# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59a5e8234fdf7d79863f6ef537e8f7bfb19a8ab2c51b9a78b0a38d19c274acffaa128acc522006870fbdb0b88ada4d9259cf614d8f32c10f340d3394c0fd8940

test:
  secret_key_base: d6006c94e904a72e5a3c76744611357ec7155bc76f6b61bbbcb04c7f529e0956b4254d3deeef7f40ceb84d3428a6f250d2890cc88e7e97218c8e7322836712d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
